### ISSUE TITLE
Working on Stretch ? How install to try ?

### ISSUE THREAD

**Issue by Ascariota** [heggink/domoticz-bluetooth-ping#1]
apt-get Bluez done but where wget your .py files to test ?

**Comment by heggink** [comment]
on your pi:
cd ~/domoticz/plugins
git clone https://github.com/heggink/domoticz-bluetooth-ping
downloads the plugin into your plugins folder
restart domoticz
from the domoticz interface: hardware -> add new hardware -> Bluetooth address presence

**Comment by Ascariota** [comment]
Ok thx it's work with stretch.
Just after x minutes automatic switch off.
I think it's the "Minutes for timeout:" parameter, but great job simple and efficient
